import { Task, Contact, Lead, User, Department } from './types';

export const mockDepartments: Department[] = [
  { id: 'Digital Infrastructure', name: 'Digital Infrastructure', createdAt: '2026-01-01' },
  { id: 'Legal & IP', name: 'Legal & IP', createdAt: '2026-01-01' },
  { id: 'Digital Engagement & Design', name: 'Digital Engagement & Design', createdAt: '2026-01-01' },
  { id: 'Global Alliance & Advocacy', name: 'Global Alliance & Advocacy', createdAt: '2026-01-01' },
  { id: 'R&D', name: 'R&D', createdAt: '2026-01-01' },
  { id: 'Business Research & Analysis', name: 'Business Research & Analysis', createdAt: '2026-01-01' },
  { id: 'Executives', name: 'Executives', createdAt: '2026-01-01' },
];

export const mockUsers: User[] = [
  {
    id: 'admin-0',
    name: 'Vishesh Aggarwal',
    email: 'admin@vertis.com',
    phone: '+1 111 222 3333',
    role: 'Administrator',
    roleLevel: 0,
    departmentId: 'Executives',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140037.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'ceo-1',
    name: 'Marcus Thorne',
    email: 'ceo@vertis.com',
    phone: '+1 222 333 4444',
    role: 'CEO',
    roleLevel: 1,
    departmentId: 'Executives',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140048.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'cso-1',
    name: 'Sophia Laurent',
    email: 'cso@vertis.com',
    phone: '+1 222 333 4445',
    role: 'CSO',
    roleLevel: 1,
    departmentId: 'Executives',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140045.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'coo-1',
    name: 'Marcus Thorne',
    email: 'coo@vertis.com',
    phone: '+1 222 333 4446',
    role: 'COO',
    roleLevel: 1,
    departmentId: 'Executives',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140042.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'coo-assoc-1',
    name: 'Alex Rivera',
    email: 'alex@vertis.com',
    phone: '+1 333 444 5555',
    role: 'COO Associate',
    roleLevel: 2,
    departmentId: 'Executives',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140041.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  // Digital Infrastructure
  {
    id: 'head-di',
    name: 'Sarah Jenkins',
    email: 'sarah.di@vertis.com',
    phone: '+1 444 555 6661',
    role: 'Department Head',
    roleLevel: 3,
    departmentId: 'Digital Infrastructure',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140047.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'senior-di',
    name: 'Michael Chen',
    email: 'michael.di@vertis.com',
    phone: '+1 555 666 7771',
    role: 'Senior Associate (I & II)',
    roleLevel: 4,
    departmentId: 'Digital Infrastructure',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140039.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'junior-di',
    name: 'Emma Watson',
    email: 'emma.di@vertis.com',
    phone: '+1 666 777 8881',
    role: 'Junior Associate',
    roleLevel: 5,
    departmentId: 'Digital Infrastructure',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140051.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  // Legal & IP
  {
    id: 'head-legal',
    name: 'Jonathan Wright',
    email: 'jonathan.legal@vertis.com',
    phone: '+1 444 555 6662',
    role: 'Department Head',
    roleLevel: 3,
    departmentId: 'Legal & IP',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140043.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'senior-legal',
    name: 'Elena Rodriguez',
    email: 'elena.legal@vertis.com',
    phone: '+1 555 666 7772',
    role: 'Senior Associate (I & II)',
    roleLevel: 4,
    departmentId: 'Legal & IP',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140044.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'junior-legal',
    name: 'Liam O\'Connor',
    email: 'liam.legal@vertis.com',
    phone: '+1 666 777 8882',
    role: 'Junior Associate',
    roleLevel: 5,
    departmentId: 'Legal & IP',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140046.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  // Digital Engagement & Design
  {
    id: 'head-design',
    name: 'Isabella Rossi',
    email: 'isabella.design@vertis.com',
    phone: '+1 444 555 6663',
    role: 'Department Head',
    roleLevel: 3,
    departmentId: 'Digital Engagement & Design',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140049.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'senior-design',
    name: 'David Miller',
    email: 'david.design@vertis.com',
    phone: '+1 555 666 7773',
    role: 'Senior Associate (I & II)',
    roleLevel: 4,
    departmentId: 'Digital Engagement & Design',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140040.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'junior-design',
    name: 'Sophie Martin',
    email: 'sophie.design@vertis.com',
    phone: '+1 666 777 8883',
    role: 'Junior Associate',
    roleLevel: 5,
    departmentId: 'Digital Engagement & Design',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140050.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  // Global Alliance & Advocacy
  {
    id: 'head-alliance',
    name: 'Arthur Morgan',
    email: 'arthur.alliance@vertis.com',
    phone: '+1 444 555 6664',
    role: 'Department Head',
    roleLevel: 3,
    departmentId: 'Global Alliance & Advocacy',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140038.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'senior-alliance',
    name: 'Chloe Dubois',
    email: 'chloe.alliance@vertis.com',
    phone: '+1 555 666 7774',
    role: 'Senior Associate (I & II)',
    roleLevel: 4,
    departmentId: 'Global Alliance & Advocacy',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140052.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'junior-alliance',
    name: 'Lucas Silva',
    email: 'lucas.alliance@vertis.com',
    phone: '+1 666 777 8884',
    role: 'Junior Associate',
    roleLevel: 5,
    departmentId: 'Global Alliance & Advocacy',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140053.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  // R&D
  {
    id: 'head-rd',
    name: 'Dr. Victor Fries',
    email: 'victor.rd@vertis.com',
    phone: '+1 444 555 6665',
    role: 'Department Head',
    roleLevel: 3,
    departmentId: 'R&D',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140054.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'senior-rd',
    name: 'Nora West',
    email: 'nora.rd@vertis.com',
    phone: '+1 555 666 7775',
    role: 'Senior Associate (I & II)',
    roleLevel: 4,
    departmentId: 'R&D',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140055.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'junior-rd',
    name: 'Barry Allen',
    email: 'barry.rd@vertis.com',
    phone: '+1 666 777 8885',
    role: 'Junior Associate',
    roleLevel: 5,
    departmentId: 'R&D',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140056.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  // Business Research & Analysis
  {
    id: 'head-analysis',
    name: 'Rachel Zane',
    email: 'rachel.analysis@vertis.com',
    phone: '+1 444 555 6666',
    role: 'Department Head',
    roleLevel: 3,
    departmentId: 'Business Research & Analysis',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140057.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'senior-analysis',
    name: 'Harvey Specter',
    email: 'harvey.analysis@vertis.com',
    phone: '+1 555 666 7776',
    role: 'Senior Associate (I & II)',
    roleLevel: 4,
    departmentId: 'Business Research & Analysis',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140058.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
  {
    id: 'junior-analysis',
    name: 'Mike Ross',
    email: 'mike.analysis@vertis.com',
    phone: '+1 666 777 8886',
    role: 'Junior Associate',
    roleLevel: 5,
    departmentId: 'Business Research & Analysis',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140059.png',
    password: 'vertis_crm',
    updatedAt: '2026-04-03',
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Design System Update',
    description: 'Update the core design system with new typography and color tokens.',
    status: 'in_progress',
    priority: 'high',
    deadline: '2026-04-10',
    assignedTo: 'ceo-1',
    assignedBy: 'admin-0',
    createdAt: '2026-04-01',
    updatedAt: '2026-04-01',
  },
  {
    id: '2',
    title: 'Client Onboarding - Acme Corp',
    description: 'Initial meeting with Acme Corp to discuss project requirements.',
    status: 'pending',
    priority: 'medium',
    deadline: '2026-04-12',
    assignedTo: 'head-1',
    assignedBy: 'ceo-1',
    createdAt: '2026-04-01',
    updatedAt: '2026-04-01',
  },
  {
    id: '3',
    title: 'Q1 Financial Review',
    description: 'Prepare financial reports for the Q1 review meeting.',
    status: 'reviewed',
    priority: 'high',
    deadline: '2026-04-05',
    assignedTo: 'ceo-1',
    assignedBy: 'admin-0',
    createdAt: '2026-04-01',
    updatedAt: '2026-04-01',
  },
  {
    id: '4',
    title: 'Marketing Campaign Launch',
    description: 'Finalize assets for the upcoming spring marketing campaign.',
    status: 'completed',
    priority: 'medium',
    deadline: '2026-03-30',
    assignedTo: 'emma-1',
    assignedBy: 'head-1',
    createdAt: '2026-04-01',
    updatedAt: '2026-04-01',
  },
  {
    id: '5',
    title: 'Server Migration Phase 2',
    description: 'Migrate legacy databases to the new cloud infrastructure.',
    status: 'in_progress',
    priority: 'high',
    deadline: '2026-04-15',
    assignedTo: 'michael-1',
    assignedBy: 'ceo-1',
    createdAt: '2026-04-02',
    updatedAt: '2026-04-02',
  },
  {
    id: '6',
    title: 'Market Competitor Analysis',
    description: 'Research top 5 competitors and their Q1 performance.',
    status: 'pending',
    priority: 'medium',
    deadline: '2026-04-20',
    assignedTo: 'david-1',
    assignedBy: 'ceo-1',
    createdAt: '2026-04-02',
    updatedAt: '2026-04-02',
  },
  {
    id: '7',
    title: 'New Patent Application',
    description: 'Draft the technical specifications for the new AI algorithm patent.',
    status: 'pending',
    priority: 'high',
    deadline: '2026-04-25',
    assignedTo: 'emma-1',
    assignedBy: 'head-1',
    createdAt: '2026-04-02',
    updatedAt: '2026-04-02',
  },
];

export const mockContacts: Contact[] = [
  // Employees
  ...mockUsers.map(user => ({
    id: `emp-${user.id}`,
    name: user.name,
    email: user.email,
    phone: user.phone || '',
    company: 'Vertis',
    status: 'employee' as const,
    lastContacted: user.updatedAt,
    avatarUrl: user.avatarUrl,
    role: user.role,
    roleLevel: user.roleLevel,
    departmentId: user.departmentId,
  })),
  // External Contacts
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1 234 567 890',
    company: 'TechFlow',
    status: 'customer',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140040.png',
    lastContacted: '2026-03-28',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@acmecorp.com',
    phone: '+1 987 654 321',
    company: 'Acme Corp',
    status: 'prospect',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140044.png',
    lastContacted: '2026-04-01',
  },
  {
    id: '3',
    name: 'Robert Brown',
    email: 'robert@global.com',
    phone: '+1 555 123 456',
    company: 'Global Logistics',
    status: 'customer',
    avatarUrl: 'https://cdn-icons-png.flaticon.com/512/4140/4140042.png',
    lastContacted: '2026-04-02',
  },
];

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Global Logistics Expansion',
    company: 'Global Logistics',
    value: 45000,
    status: 'proposal',
    probability: 60,
  },
  {
    id: '2',
    name: 'New SaaS Platform',
    company: 'CloudNine',
    value: 120000,
    status: 'negotiation',
    probability: 85,
  },
];
